<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bombons de Chocolate Caja Roja</name>
   <tag></tag>
   <elementGuidId>6a16253f-8b7a-448f-96c7-8e7aea4c7c85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide22']/div/div/div/div[3]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba6e8e0b-3151-4d89-aeb2-16bfe456c8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pwc-tile--description col-tile--description</value>
      <webElementGuid>7e19d9a4-2e95-4f57-9de2-78b27c6c7c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/produto/bombons-de-chocolate-caja-roja-nestle-4155290.html</value>
      <webElementGuid>ebf5ab4e-e7dd-455b-8a3b-3ec335a85063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4fe81917-f333-4eb9-ac3f-92b56e6fd90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bombons de Chocolate Caja Roja</value>
      <webElementGuid>3ba9495d-47ba-47ae-a016-6d11d2b70da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide22&quot;)/div[@class=&quot;product&quot;]/div[@class=&quot;product-tile pid-4155290   ct-product-tile col-product-tile&quot;]/div[@class=&quot;ct-inner-tile-wrap col-inner-tile-wrap row no-gutters justify-content-center align-content-start&quot;]/div[@class=&quot;ct-tile-body col col-sm-auto&quot;]/div[@class=&quot;ct-pdp-details ct-pdp-details-carousel&quot;]/div[@class=&quot;ct-pdp-link col-pdp-link&quot;]/a[@class=&quot;pwc-tile--description col-tile--description&quot;]</value>
      <webElementGuid>fee5baf2-4f1d-434d-afbc-769a09a45fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide22']/div/div/div/div[3]/div/div/a</value>
      <webElementGuid>bad1df7f-7b41-4be7-b495-20beaf0f43b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bombons de Chocolate Caja Roja')]</value>
      <webElementGuid>75e565b9-8910-4163-90e4-1176390b7e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/produto/bombons-de-chocolate-caja-roja-nestle-4155290.html')])[2]</value>
      <webElementGuid>50ab498f-66c4-4907-9fe3-3becda1fe151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[3]/div/div/a</value>
      <webElementGuid>bbefc128-1d97-4de8-8662-bd2eb8aa8c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/produto/bombons-de-chocolate-caja-roja-nestle-4155290.html' and (text() = 'Bombons de Chocolate Caja Roja' or . = 'Bombons de Chocolate Caja Roja')]</value>
      <webElementGuid>60cd0655-1af2-4f75-81e0-dc33ed041c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
