<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ClubeContinenteDoBebJunte-seAoClube</name>
   <tag></tag>
   <elementGuidId>e7da7248-e86a-4a03-a50d-44af2769e740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slick-slide10 > div.experience-component.experience-commerce_assets-imageAndText > div.ITC-container.js-itc-container > div.row.ITC-row > div.col-12 > figure.ITC-figure.image-component > a.ITC-image-link > picture.intrinsic.intrinsic--itc-large > img.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide10']/div/div/div/div/figure/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>949df17b-100f-4b52-984a-d939efb2afd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyloaded</value>
      <webElementGuid>bbc0087d-c40f-43b2-98a6-571f6c45132b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f3dc6ffa-d521-470e-9cfe-fb394e4c6f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw7e333419/images/homepage/continente-comunidade/2024/01/2024_S04_clubebebe_3-TILES_24-comunidade_own.jpg?sw=540&amp;sh=540&amp;sm=fit</value>
      <webElementGuid>1637c53c-b5cc-4a12-9a92-55137a83173f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Clube Continente do Bebé</value>
      <webElementGuid>21ad7288-5908-4479-8f79-09015e0f94cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Clube Continente do Bebé</value>
      <webElementGuid>e5948c78-1e65-460f-9c7c-b8c9162c1ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw7e333419/images/homepage/continente-comunidade/2024/01/2024_S04_clubebebe_3-TILES_24-comunidade_own.jpg?sw=540&amp;sh=540&amp;sm=fit</value>
      <webElementGuid>8573908b-3d02-43bf-afb5-7f0f2b4114e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide10&quot;)/div[@class=&quot;experience-component experience-commerce_assets-imageAndText&quot;]/div[@class=&quot;ITC-container js-itc-container&quot;]/div[@class=&quot;row ITC-row&quot;]/div[@class=&quot;col-12&quot;]/figure[@class=&quot;ITC-figure image-component&quot;]/a[@class=&quot;ITC-image-link&quot;]/picture[@class=&quot;intrinsic intrinsic--itc-large&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>468cb352-8e8a-4f22-b7a6-bc71999d18f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide10']/div/div/div/div/figure/a/picture/img</value>
      <webElementGuid>84d4b0aa-4ba5-425e-8b9f-d51eee72a983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Clube Continente do Bebé']</value>
      <webElementGuid>69b9be37-6769-4ac6-9c6f-03148ef832b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div/div/figure/a/picture/img</value>
      <webElementGuid>db098db8-4a95-48e8-bf94-9cb42ea7f649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Clube Continente do Bebé' and @title = 'Clube Continente do Bebé' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw7e333419/images/homepage/continente-comunidade/2024/01/2024_S04_clubebebe_3-TILES_24-comunidade_own.jpg?sw=540&amp;sh=540&amp;sm=fit']</value>
      <webElementGuid>54411019-6eda-4df6-acec-3b277901e238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
