<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ContinenteBio</name>
   <tag></tag>
   <elementGuidId>d982a4ae-e925-4f7c-a729-e0c3bdbaae48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='col-homepage']/div/div/div/div/div[7]/div/div[2]/div[3]/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a2c1ef2-3e29-4d18-b396-05edb6de09f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyloaded</value>
      <webElementGuid>6255166a-e843-44df-a4c5-ca8159c5dcc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>e0bdb8a7-eeb7-453c-8716-0a93db24766f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwd4b2b3ad/images/pages/marca-propria/continente-bio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>f11f9baf-07e9-453f-bfcc-ce4290a3984c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Marca Continente Bio</value>
      <webElementGuid>b2fba72c-61b6-438b-aae8-d24985d2aac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marca Continente Bio</value>
      <webElementGuid>c8dd31ef-77be-4ad4-afdc-ca4193c6cb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwd4b2b3ad/images/pages/marca-propria/continente-bio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>aecc031c-eed9-4896-baf8-b6a24f377c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col-homepage&quot;)/div[@class=&quot;fullpage&quot;]/div[@class=&quot;no-padding--sides&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;experience-component experience-commerce_layouts-popularCategories&quot;]/div[@class=&quot;popular-categories&quot;]/div[@class=&quot;row mx-0 category-layout-grid&quot;]/div[@class=&quot;col-sm-2 col-4 category-tile-wrapper&quot;]/div[@class=&quot;image-cropper&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--square&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>127f280f-e6a9-4e20-9a7e-55588589974c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='col-homepage']/div/div/div/div/div[7]/div/div[2]/div[3]/div/a/picture/img</value>
      <webElementGuid>85bc924f-30d3-451c-8715-14502607fc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Marca Continente Bio']</value>
      <webElementGuid>b12c6c7b-27d5-4ffe-bf65-1b27d38681a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div[3]/div/a/picture/img</value>
      <webElementGuid>a3d9f526-97c4-4d71-b680-7fe7d4034204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Marca Continente Bio' and @title = 'Marca Continente Bio' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwd4b2b3ad/images/pages/marca-propria/continente-bio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit']</value>
      <webElementGuid>78f52db0-9ff5-4919-b591-f58358c25bd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
