<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ContinenteEquilibrio</name>
   <tag></tag>
   <elementGuidId>f4299387-9f09-4293-a937-d849a371b96b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='col-homepage']/div/div/div/div/div[7]/div/div[2]/div[2]/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc945425-6b8f-4892-b5eb-d28292b2f2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyloaded</value>
      <webElementGuid>fc9842e6-7cd5-4ec9-8d6a-83d74ae786e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>bf03fb68-8536-4023-bae7-9aaf3304aadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwde2d0b6d/images/pages/marca-propria/continente-equilibrio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>993e8003-482b-4969-9cd8-30f185bb0899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Marca Continente Equilíbrio</value>
      <webElementGuid>6fb91a3f-6cc9-4d58-8058-43c1ccbb181f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marca Continente Equilíbrio</value>
      <webElementGuid>de1c3ef0-f348-42f7-9308-e5ad56c760fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwde2d0b6d/images/pages/marca-propria/continente-equilibrio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>73a05ba5-4288-4f41-a23e-717a6cc9772d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col-homepage&quot;)/div[@class=&quot;fullpage&quot;]/div[@class=&quot;no-padding--sides&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;experience-component experience-commerce_layouts-popularCategories&quot;]/div[@class=&quot;popular-categories&quot;]/div[@class=&quot;row mx-0 category-layout-grid&quot;]/div[@class=&quot;col-sm-2 col-4 category-tile-wrapper&quot;]/div[@class=&quot;image-cropper&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--square&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>997b548e-8d6b-4272-bcbc-b9b8ba75390c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='col-homepage']/div/div/div/div/div[7]/div/div[2]/div[2]/div/a/picture/img</value>
      <webElementGuid>68b94c43-2c84-4c51-b3b5-10753412cce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Marca Continente Equilíbrio']</value>
      <webElementGuid>132d86fa-e12d-43e8-aaf1-4f061606ce59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div[2]/div/a/picture/img</value>
      <webElementGuid>2ebfb2fe-5acb-463d-a764-ff8a02af746c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Marca Continente Equilíbrio' and @title = 'Marca Continente Equilíbrio' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwde2d0b6d/images/pages/marca-propria/continente-equilibrio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit']</value>
      <webElementGuid>1a2a0888-63cb-474a-aff1-4f28f8c138e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
