<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Campanhas</name>
   <tag></tag>
   <elementGuidId>ebfc8f33-bd3e-4fa3-9e04-744dc78fa4ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontent']/div[3]/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a0a9748-a45b-43e6-b87a-c8eb7d9d62dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.continente.pt/campanhas-1/</value>
      <webElementGuid>74b5d01e-c25b-42b9-b73d-c89c83c731bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipaper-top-link</value>
      <webElementGuid>5ae627df-513d-45dd-9b5c-17bc7a58e379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Campanhas</value>
      <webElementGuid>af4fb6ad-5942-4eea-a955-cdca85e8ae53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;padding-sm-down-x-15 padding-md-up-x-70 ipaper-top--links&quot;]/div[@class=&quot;content-asset&quot;]/div[@class=&quot;ipaper-top-links--wrapper text-center&quot;]/div[@class=&quot;ipaper-top-links--inner-wrapper d-flex justify-content-sm-center&quot;]/div[@class=&quot;ipaper-top-links--item-wrapper&quot;]/a[@class=&quot;ipaper-top-link&quot;]</value>
      <webElementGuid>683b2550-369f-40cd-bdb8-754ccaec1906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div[3]/div/div/div/div[2]/a</value>
      <webElementGuid>f81e9ae8-e81c-448a-82db-0164ddcb01b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Campanhas')])[2]</value>
      <webElementGuid>aa0f154e-6182-4c28-b7a6-319f1e93fa83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.continente.pt/campanhas-1/')]</value>
      <webElementGuid>e0d74441-284d-4753-bb26-11c0233fa4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/a</value>
      <webElementGuid>80aa4698-9dae-4a32-9c4e-b4383599d66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.continente.pt/campanhas-1/' and (text() = 'Campanhas' or . = 'Campanhas')]</value>
      <webElementGuid>1133f55d-6e65-45c1-91cc-d28243c4be9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
