<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Comprar</name>
   <tag></tag>
   <elementGuidId>39c27222-e8bd-4e6e-8b63-c81d893bd81e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.minicart-add-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='minicart-footer']/div/div[2]/div[2]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f667320-1bf1-4f88-9804-bc498531f35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minicart-add-label</value>
      <webElementGuid>56995db3-f09f-4ebd-9a8f-fa9957882a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprar</value>
      <webElementGuid>e4ebe316-5f94-4085-bcd5-381bd5347e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minicart-footer&quot;)/div[@class=&quot;minicart-footer&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col&quot;]/a[@class=&quot;button button--primary minicart-add-button&quot;]/span[@class=&quot;minicart-add-label&quot;]</value>
      <webElementGuid>c47e3bab-05ff-45a0-8957-7d997ef50a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='minicart-footer']/div/div[2]/div[2]/a/span[2]</value>
      <webElementGuid>2d37a9c6-874a-4737-81e2-8e2554a4d154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/a/span[2]</value>
      <webElementGuid>85b29484-627a-4637-8986-b35f65821610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Comprar' or . = 'Comprar')]</value>
      <webElementGuid>7c6449c6-6b43-4483-9086-1eb0f31ef39f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
