<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Preos Bombsticos_lazyloaded</name>
   <tag></tag>
   <elementGuidId>3302ad48-d94b-43cf-a389-a1ddc10eea89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='col-homepage']/div/div/div/div/div[4]/div/div[2]/div[4]/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ba9a66ca-2cdd-4ed6-b6af-4c8f1056a568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyloaded</value>
      <webElementGuid>f02ebf54-d8c3-49ad-a5c6-3ade5b0aa4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3cffbe10-cc15-4721-a05a-f6500d1f9772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw188e46d4/images/homepage/categorias/2024/02/2024_CIRCLES_sabor-brasil_int.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>9d112244-619f-456b-91f8-105d1e9cd8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sabor a Brasil</value>
      <webElementGuid>a418bc75-074c-4768-babe-bb7680a7a49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sabor a Brasil</value>
      <webElementGuid>6d035bdc-4dda-4b31-81d8-d45bc50ce5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw188e46d4/images/homepage/categorias/2024/02/2024_CIRCLES_sabor-brasil_int.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>8b0d0343-40c8-44a5-a414-68b3db1d43e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col-homepage&quot;)/div[@class=&quot;fullpage&quot;]/div[@class=&quot;no-padding--sides&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;experience-component experience-commerce_layouts-popularCategories&quot;]/div[@class=&quot;popular-categories&quot;]/div[@class=&quot;row mx-0 category-layout-grid&quot;]/div[@class=&quot;col-sm-2 col-4 category-tile-wrapper&quot;]/div[@class=&quot;image-cropper&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--square&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>f03f5f3a-68a2-4b9e-945a-fb9b5c8a91e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='col-homepage']/div/div/div/div/div[4]/div/div[2]/div[4]/div/a/picture/img</value>
      <webElementGuid>0bac5bad-93ec-4eea-b5f8-051aa5728f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sabor a Brasil']</value>
      <webElementGuid>69757603-cf83-400a-94d9-b52ae9fcae2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/picture/img</value>
      <webElementGuid>581603c7-f7ec-47cb-ac4f-9ce6e51a6ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sabor a Brasil' and @title = 'Sabor a Brasil' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw188e46d4/images/homepage/categorias/2024/02/2024_CIRCLES_sabor-brasil_int.jpg?sw=270&amp;sh=270&amp;sm=fit']</value>
      <webElementGuid>9a5d3a36-54d4-48cf-aa5c-853a336091e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
