<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ct-tile-image lazyloaded</name>
   <tag></tag>
   <elementGuidId>3c6b540e-c1ea-4219-94a6-e7b974d69af4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ct-tile-image.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb7c26bb-a3ad-46b3-95a2-757d4c8773c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-tile-image lazyloaded</value>
      <webElementGuid>4f85cdf4-3ee5-413f-8c81-46ace751a60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5e02d9df-cb45-45b8-9fe2-ed617b77866d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-continente-Site/-/default/dw8b8575b8/images/noimagelarge_product.png';</value>
      <webElementGuid>e2901682-1ad2-4267-98df-adf5ae628073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw198cb76a/images/col/588/5888634-cima.jpg?sw=280&amp;sh=280</value>
      <webElementGuid>cb396e01-252e-4b87-866f-14a594165150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Carne de Porco à Portuguesa</value>
      <webElementGuid>50f2e37d-4133-4917-bf1b-1271f38f91fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Carne de Porco à Portuguesa</value>
      <webElementGuid>5441d7c6-e13d-44ab-b6fd-98dc65ac2a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw198cb76a/images/col/588/5888634-cima.jpg?sw=280&amp;sh=280</value>
      <webElementGuid>6c743603-49c4-419c-a1bd-e7e7ddb3ac98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;container-margin search-results&quot;]/div[@class=&quot;search-results-grid&quot;]/div[@class=&quot;results-section&quot;]/div[@class=&quot;row product-grid no-gutters gtm-list&quot;]/div[@class=&quot;col-12 col-sm-3 col-lg-2 productTile&quot;]/div[@class=&quot;product&quot;]/div[@class=&quot;product-tile pid-5888634 ct-product-tile col-product-tile data-layer-pushed&quot;]/div[@class=&quot;ct-inner-tile-wrap col-inner-tile-wrap row no-gutters justify-content-center align-content-start&quot;]/div[@class=&quot;ct-image-container col-4 col-sm&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--square intrinsic--square&quot;]/img[@class=&quot;ct-tile-image lazyloaded&quot;]</value>
      <webElementGuid>695ffe00-17eb-4d32-8b82-1dee982d5131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='']</value>
      <webElementGuid>1d4bf35d-fd9a-4e63-b484-4b33281146a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div[3]/div[4]/div[2]/div[5]/div/div/div/div/div/a/picture/img</value>
      <webElementGuid>2b70ccf4-1c09-4165-9377-686e174a48be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Carne de Porco à Portuguesa']</value>
      <webElementGuid>947d35d0-635d-4002-9093-58cff0feda08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/picture/img</value>
      <webElementGuid>c54aada7-4637-40d5-9c78-351023d9e9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Carne de Porco à Portuguesa' and @title = 'Carne de Porco à Portuguesa' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw198cb76a/images/col/588/5888634-cima.jpg?sw=280&amp;sh=280']</value>
      <webElementGuid>4ea6a815-0151-4094-8da9-14762af77ae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
