<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_adicionar todos</name>
   <tag></tag>
   <elementGuidId>3779aac0-f34e-44ec-bb12-ce10a945d4c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.col-button.button--primary.col-button--primary.js-add-to-cart-my-list.add-all-btn.product-set-list.ct-my-products--has-products</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f75991cb-1dc1-424b-8bc5-5e603fdea834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec6e4a55-5fbc-489a-861e-870a31f760ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button col-button button--primary col-button--primary js-add-to-cart-my-list add-all-btn product-set-list ct-my-products--has-products</value>
      <webElementGuid>ed407b2c-3b9e-48fe-949c-65d118e531b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>foodchocolatequente</value>
      <webElementGuid>d0c2ad2c-a0b2-4a30-9d7d-87c016944c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity-value</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>7bc144e2-0832-4eee-a03d-9945b741d4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>adicionar todos</value>
      <webElementGuid>60957d5e-d782-44a2-9e20-146c746b4d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.continente.pt/on/demandware.store/Sites-continente-Site/default/Cart-AddProductList</value>
      <webElementGuid>55bc2802-09f1-47f0-af59-fffd771691e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
adicionar todos
</value>
      <webElementGuid>7e9b9373-2f58-46a2-978a-3a2aeffbba83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;row no-gutters product-detail product-wrapper&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row no-gutters product-images-container&quot;]/div[@class=&quot;col-12 col-sm-7 col-md-6 product-name-details&quot;]/div[@class=&quot;product-name-details--wrapper product-set-list pwc-border--radius ct-my-products--has-products&quot;]/div[@class=&quot;row attributes&quot;]/div[@class=&quot;ct-my-products--add-to-cart-container product-set-list js-add-to-cart-container js-add-to-cart-container--large ct-my-products--has-products&quot;]/button[@class=&quot;button col-button button--primary col-button--primary js-add-to-cart-my-list add-all-btn product-set-list ct-my-products--has-products&quot;]</value>
      <webElementGuid>fbf85727-4fe7-48bc-8878-af887de3965a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>02fcc512-bcfd-4bb1-aab5-9bc976dce2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div/div[2]/div[2]/div/div[3]/div[4]/button</value>
      <webElementGuid>8d9cf252-f746-43eb-bf50-12f273814c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>7f865e2e-deed-441f-9ce8-61eedd92f41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
adicionar todos
' or . = '
adicionar todos
')]</value>
      <webElementGuid>3d4e0ff2-3d35-42d0-8833-efe9fbe0a2b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
