<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Utilizar apenas os cookies necessrios</name>
   <tag></tag>
   <elementGuidId>abb90564-e687-4e35-b1fa-cb9300a6fadf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CybotCookiebotDialogBodyButtonDecline']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CybotCookiebotDialogBodyButtonDecline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be6e3bec-b72f-4c20-9103-bb1c2ec2c6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyButtonDecline</value>
      <webElementGuid>11d6ae87-85fb-424b-b0f5-eea819bc8777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyButton</value>
      <webElementGuid>cde209f6-40d1-49be-a8c4-3cab20d1ae98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c6d063a6-9799-467a-8bbf-f0fe58ee1ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>pt</value>
      <webElementGuid>9efd4419-3846-4030-9ce8-9fed1f3622b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Utilizar apenas os cookies necessários</value>
      <webElementGuid>551e2a1b-7f75-4d6a-b8a4-d1a7f62de9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CybotCookiebotDialogBodyButtonDecline&quot;)</value>
      <webElementGuid>dd153d1d-407d-4212-930f-6de1a29ab667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CybotCookiebotDialogBodyButtonDecline']</value>
      <webElementGuid>b3f9d749-2327-44c0-8983-88e55ffa6e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CybotCookiebotDialogBodyButtonsWrapper']/button</value>
      <webElementGuid>d55013e9-f10f-4b26-9ad8-7f77283dd5b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>78610564-b571-422a-aec3-731eae4de92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CybotCookiebotDialogBodyButtonDecline' and (text() = 'Utilizar apenas os cookies necessários' or . = 'Utilizar apenas os cookies necessários')]</value>
      <webElementGuid>41822a88-088b-4776-b4f7-76bde5cc148f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
