<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ct-tile-image lazyloaded</name>
   <tag></tag>
   <elementGuidId>66107871-64e6-4874-9ad1-3027b7b6e94f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-tile.pid-4679597.ct-product-tile.col-product-tile.data-layer-pushed > div.ct-inner-tile-wrap.col-inner-tile-wrap.row.no-gutters.justify-content-center.align-content-start > div.ct-image-container.col-4.col-sm > a > picture.intrinsic.intrinsic--square.intrinsic--square > img.ct-tile-image.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id=''])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>19905040-7c67-41d6-b802-03f43fbfa634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-tile-image lazyloaded</value>
      <webElementGuid>a2cfb3d3-9c60-43d9-90e2-1e56a38bb0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>b86f55f1-d3e4-480b-9c39-76dcf4fd0eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-continente-Site/-/default/dw8b8575b8/images/noimagelarge_product.png';</value>
      <webElementGuid>d93a8117-94a7-4c4c-b25e-0036e5745516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwbad38a64/images/col/467/4679597-frente.jpg?sw=280&amp;sh=280</value>
      <webElementGuid>4013a112-64ae-41f3-b176-e7dd04b192a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Leite UHT Magro sem Lactose</value>
      <webElementGuid>5420d673-b491-4be9-b88e-37ce4ad99800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Leite UHT Magro sem Lactose</value>
      <webElementGuid>7817296c-8d00-4593-a833-1008c311e148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwbad38a64/images/col/467/4679597-frente.jpg?sw=280&amp;sh=280</value>
      <webElementGuid>49d8136f-7c17-45e6-ab4c-60df731b89e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-search-results&quot;)/div[@class=&quot;search-results-grid&quot;]/div[@class=&quot;results-section&quot;]/div[@class=&quot;row product-grid no-gutters gtm-list&quot;]/div[@class=&quot;col-12 col-sm-3 col-lg-2 productTile&quot;]/div[@class=&quot;product&quot;]/div[@class=&quot;product-tile pid-4679597 ct-product-tile col-product-tile data-layer-pushed&quot;]/div[@class=&quot;ct-inner-tile-wrap col-inner-tile-wrap row no-gutters justify-content-center align-content-start&quot;]/div[@class=&quot;ct-image-container col-4 col-sm&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--square intrinsic--square&quot;]/img[@class=&quot;ct-tile-image lazyloaded&quot;]</value>
      <webElementGuid>849a32b5-dcbc-4fc5-996c-718cc8ee0e44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id=''])[5]</value>
      <webElementGuid>c66494a2-f313-4cc1-90b6-d09da2e8659e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-search-results']/div/div[2]/div[3]/div[5]/div/div/div/div[2]/a/picture/img</value>
      <webElementGuid>5c6046d4-db55-4661-943c-0077d601e7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Leite UHT Magro sem Lactose']</value>
      <webElementGuid>a34592e8-e2de-4c10-afc8-f69ec1ed033a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/picture/img</value>
      <webElementGuid>080d9e74-8b61-410d-8d4f-066a706e7644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Leite UHT Magro sem Lactose' and @title = 'Leite UHT Magro sem Lactose' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwbad38a64/images/col/467/4679597-frente.jpg?sw=280&amp;sh=280']</value>
      <webElementGuid>39dc8456-fbe6-4290-b014-b2eba4df480c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
