<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>45ff6f93-90da-4120-aacb-fb714527fb76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;receitas&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='infoIconSliderReceitas-39341f6d-c5e7-45ee-bb66-455a4b37eee3']/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94be1497-c994-46d2-9de7-9a2fe3103231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f59fc3a9-3a88-4453-993c-3bfd2cabd301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/BrandFundamentals/Bra-098.svg</value>
      <webElementGuid>7c18d8eb-58e7-47db-be68-0d0e88bf8539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>144</value>
      <webElementGuid>196e1957-22bd-4d16-8d23-b26d7d23b19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>144</value>
      <webElementGuid>0b9a4f2b-b868-481a-b57f-017a6f42279b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>receitas</value>
      <webElementGuid>841241ed-1728-4ccc-aa3f-d6af2f69f040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infoIconSliderReceitas-39341f6d-c5e7-45ee-bb66-455a4b37eee3&quot;)/figure[1]/img[1]</value>
      <webElementGuid>3fabf881-1dc8-4d9c-85d9-15c069f51597</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='infoIconSliderReceitas-39341f6d-c5e7-45ee-bb66-455a4b37eee3']/figure/img</value>
      <webElementGuid>383b67a9-005c-4a49-9b27-2c636eb802e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='receitas']</value>
      <webElementGuid>26fc3248-9063-4a26-b17f-7342942852ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/a/figure/img</value>
      <webElementGuid>cea7f988-019c-48f9-8c99-6b339a77b78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/BrandFundamentals/Bra-098.svg' and @alt = 'receitas']</value>
      <webElementGuid>7883be3b-2e0e-47be-b0c9-192274c8cc6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
