<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-fluid lazyloaded</name>
   <tag></tag>
   <elementGuidId>b59cceb6-3b2c-4612-851e-415df6bf3952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontent']/div/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f452be40-ed38-4de9-bf78-bbd4f3bef172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>App Continente Online</value>
      <webElementGuid>ab85f3d9-e19b-43f6-ac70-7b43046ba656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid lazyloaded</value>
      <webElementGuid>af542a20-0db4-48fb-ba73-87a79cde79b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>b5b7050f-3c44-46ce-8ff4-4e6605dcd450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://static.continente.pt/images/Continente/Images/Banner/P%C3%A1gina_app/appcontinente_mobile.png</value>
      <webElementGuid>7e56f4de-a412-4d76-9ccd-3a5557f504d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>App Continente Online</value>
      <webElementGuid>ec752671-766c-400f-8619-dcd9138b72dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.continente.pt/images/Continente/Images/Banner/P%C3%A1gina_app/appcontinente_mobile.png</value>
      <webElementGuid>71470b6e-44ee-42e5-9c1b-5fc808ec0965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[1]/a[1]/picture[1]/img[@class=&quot;img-fluid lazyloaded&quot;]</value>
      <webElementGuid>97eb49d9-4f83-4731-8b79-a93d5f88d962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/a/picture/img</value>
      <webElementGuid>96390833-a34d-485d-bdc4-3839895db9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='App Continente Online']</value>
      <webElementGuid>52e5b3bc-c47d-4586-992d-a5827dd2d281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>14ea12e9-c428-4002-8e74-509e534b3645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'App Continente Online' and @title = 'App Continente Online' and @src = 'https://static.continente.pt/images/Continente/Images/Banner/P%C3%A1gina_app/appcontinente_mobile.png']</value>
      <webElementGuid>5cb0b2f7-2197-4ae6-999c-f8d0c003aea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
