<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_lazyloaded</name>
   <tag></tag>
   <elementGuidId>65e89a97-c075-4661-b4b4-9a7e99dbd866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>picture.intrinsic.intrinsic--itc-large > img.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide00']/div/div/div/div/figure/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ea5f1471-1cb4-4606-9674-601e8f7a2b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyloaded</value>
      <webElementGuid>4d7cf4e2-c1e9-4362-af66-c7e7d43401fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f5bce64b-c809-4431-b2e1-35e82ed67e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwa351be8d/images/pages/campanhas/2024/02/2024_S06_3-TILES_50-peixe-marisco-bacalhau_peixaria_int.jpg?sw=540&amp;sh=540&amp;sm=fit</value>
      <webElementGuid>83c54d2f-ab55-45ee-8d80-c8b486593dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Até 40% numa seleção de Peixe, Marisco e Bacalhau</value>
      <webElementGuid>64671e24-22f0-4fe0-b838-15de9f643447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Até 40% numa seleção de Peixe, Marisco e Bacalhau</value>
      <webElementGuid>7101dc9f-2c5f-40b6-804a-917b1f2af44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwa351be8d/images/pages/campanhas/2024/02/2024_S06_3-TILES_50-peixe-marisco-bacalhau_peixaria_int.jpg?sw=540&amp;sh=540&amp;sm=fit</value>
      <webElementGuid>5e4b576f-013f-4faf-af63-ded77e91df6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide00&quot;)/div[@class=&quot;experience-component experience-commerce_assets-imageAndText&quot;]/div[@class=&quot;ITC-container js-itc-container&quot;]/div[@class=&quot;row ITC-row&quot;]/div[@class=&quot;col-12&quot;]/figure[@class=&quot;ITC-figure image-component&quot;]/a[@class=&quot;ITC-image-link&quot;]/picture[@class=&quot;intrinsic intrinsic--itc-large&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>9e836322-087f-406b-b349-36127e06ae7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide00']/div/div/div/div/figure/a/picture/img</value>
      <webElementGuid>a1dd0315-9174-4383-9b4b-d96896d6f90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Até 40% numa seleção de Peixe, Marisco e Bacalhau']</value>
      <webElementGuid>ac5b1522-5e47-47db-ae68-1741794fe32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>9e2d4dbf-1158-4966-b461-f553775db093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Até 40% numa seleção de Peixe, Marisco e Bacalhau' and @title = 'Até 40% numa seleção de Peixe, Marisco e Bacalhau' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwa351be8d/images/pages/campanhas/2024/02/2024_S06_3-TILES_50-peixe-marisco-bacalhau_peixaria_int.jpg?sw=540&amp;sh=540&amp;sm=fit']</value>
      <webElementGuid>ce4755e8-a72a-4f66-a92b-ff3d42b3fba3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
