<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PequenoAlmoco</name>
   <tag></tag>
   <elementGuidId>4d233ac0-4431-46ce-a98a-a693394fb130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#infoIconsSLider-7d3d3f0d-e98d-46c2-8357-fbf795c89097 > figure > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='infoIconsSLider-7d3d3f0d-e98d-46c2-8357-fbf795c89097']/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3af0d2bb-4ebb-4ee1-89ea-3b548c1f9f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>03608e97-dc0b-41d9-b585-e53de19dc09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/media/o33giwmm/bra-006.svg</value>
      <webElementGuid>a214662e-f600-48b4-b63d-4efb8254ff26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>144</value>
      <webElementGuid>cf9c3d24-0f7c-4454-b5fa-0db192645357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>144</value>
      <webElementGuid>e2b06068-f3af-4315-a01c-ff41ac6bdae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;infoIconsSlider&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;infoIconsSlider__swiperSlider swiper-container swiper-container-initialized swiper-container-horizontal&quot;]/div[@class=&quot;swiper-wrapper&quot;]/article[@class=&quot;iconItem swiper-slide swiper-slide-prev&quot;]/a[@id=&quot;infoIconsSLider-7d3d3f0d-e98d-46c2-8357-fbf795c89097&quot;]/figure[1]/img[1]</value>
      <webElementGuid>912b7c5e-3671-4202-acab-16988a46c3f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='infoIconsSLider-7d3d3f0d-e98d-46c2-8357-fbf795c89097']/figure/img</value>
      <webElementGuid>807ac10b-8067-4147-85ce-acc78f6696ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[9]/a/figure/img</value>
      <webElementGuid>cd57d8db-3aa2-4ec0-a3c2-ae15d7b9433d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/media/o33giwmm/bra-006.svg']</value>
      <webElementGuid>ee451e6e-1032-49c0-a02f-075474396b04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
