<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-fluid pwc-border--radius</name>
   <tag></tag>
   <elementGuidId>431ddbca-f3ab-47af-b712-a89a3e0eed5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Barras, Bolachas e Chocolates&quot;] > picture.intrinsic.intrinsic--category-tile > img.img-fluid.pwc-border--radius</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide03']/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>24a1f220-d12f-42a4-88c3-90442dc83704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid pwc-border--radius</value>
      <webElementGuid>e88f96af-030f-4f37-8466-c2c6aee0b3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-global-navigation-catalog/default/dw0a9548cb/images/marcas/marca-propria/standard/bio-barras-bolachas.jpg?sw=600&amp;sh=150</value>
      <webElementGuid>816f5123-b8ab-4e60-a80b-b6167aa06796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Barras, Bolachas e Chocolates</value>
      <webElementGuid>922c6ab6-8a0c-404d-b4f6-15c7360e56f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Barras, Bolachas e Chocolates</value>
      <webElementGuid>9d575050-1a42-48e1-afbe-c3c1a2fc9ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide03&quot;)/div[@class=&quot;category-tile-image pwc-border--radius&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--category-tile&quot;]/img[@class=&quot;img-fluid pwc-border--radius&quot;]</value>
      <webElementGuid>be4074cf-00b8-49a9-924f-3c96d33e5ceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide03']/div/a/picture/img</value>
      <webElementGuid>9f445920-177a-4970-a5ff-1fd3acd053e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Barras, Bolachas e Chocolates']</value>
      <webElementGuid>8e27fff4-01c5-4999-be29-200ac64f1bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/picture/img</value>
      <webElementGuid>f70ed2f2-1929-4237-aaca-19850c0281ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-global-navigation-catalog/default/dw0a9548cb/images/marcas/marca-propria/standard/bio-barras-bolachas.jpg?sw=600&amp;sh=150' and @alt = 'Barras, Bolachas e Chocolates' and @title = 'Barras, Bolachas e Chocolates']</value>
      <webElementGuid>47c861d7-f49c-4d56-81a4-0d5561462c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
