<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Carrinho</name>
   <tag></tag>
   <elementGuidId>0feadd4b-24bc-47a1-9c16-8d178c2ebb73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.svg-inline.icon-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;brand-header&quot;]/nav/div/div[1]/div[2]/div[3]/div[1]/a/div/div[1]/span[1]/svg/path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a944c834-4810-4baa-a4d6-96daac6fd80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline icon-cart</value>
      <webElementGuid>218d379e-9ffd-4739-8312-29a006ae0aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>0499e897-fe08-4d70-975d-3bdff86a8912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 500 500</value>
      <webElementGuid>85e87ec5-468a-44a6-b047-b6d598f4314c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>72d0ee25-8417-4a91-ba88-da8066513bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>ed6ba6a4-206f-4c4e-80c8-fb59eecc070a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brand-header&quot;)/nav[@class=&quot;nav-wrapper col-nav-wrapper&quot;]/div[@class=&quot;sticky-element navigation-shadows is-sticky&quot;]/div[@class=&quot;header-wrapper container-fluid container-margin d-flex align-items-center justify-content-between&quot;]/div[@class=&quot;user-util d-flex align-items-center&quot;]/div[@class=&quot;minicart col-minicart&quot;]/div[@class=&quot;minicart-total d-none d-md-block&quot;]/a[@class=&quot;minicart-link&quot;]/div[@class=&quot;minicart-wrapper col-icon-cart&quot;]/div[@class=&quot;target-wrap&quot;]/span[@class=&quot;svg-wrapper svg-icon-cart&quot;]/svg[@class=&quot;svg-inline icon-cart&quot;]</value>
      <webElementGuid>7cc462cf-6e83-45d8-945c-9696d3ebdc36</webElementGuid>
   </webElementProperties>
</WebElementEntity>
