<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Carto Continente</name>
   <tag></tag>
   <elementGuidId>433421df-4a00-41bc-a553-5a4fcf99e3ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footercontent']/div[2]/div/div/div[3]/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.col-md-4.d-none.d-md-block > div.content-asset > ul.ct-menu-list > li.ct-footer-link > a[title=&quot;Go to Cartão Continente&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0ee4fab-fb45-43c9-a9cc-bb3af2120ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.cartaocontinente.pt/?_gl=1*fmuffs*_ga*MTY1MDY2MjM1MC4xNzA3MjM4NTI0*_ga_56Q9X41Z3T*MTcwNzIzODUyMi4xLjAuMTcwNzIzODUyNy41OC4wLjA.</value>
      <webElementGuid>d62e2749-fa46-4348-bfa2-1452df6c5c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>61fd3009-fd8c-42e8-9bc6-ea8e7116e912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go to Cartão Continente</value>
      <webElementGuid>2b0a0ba4-769d-4c57-a039-81ef8892b7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cartão Continente</value>
      <webElementGuid>24a24989-bae2-46de-a4da-36a6aecf5a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footercontent&quot;)/div[@class=&quot;container-fluid no-padding ct-modal-dialog-secondary-grey1 ct-font--opensans-book&quot;]/div[@class=&quot;pwc-container&quot;]/div[@class=&quot;row no-gutters footer-container pwc-container--px-70&quot;]/div[@class=&quot;col-12 col-md-4 d-none d-md-block&quot;]/div[@class=&quot;content-asset&quot;]/ul[@class=&quot;ct-menu-list&quot;]/li[@class=&quot;ct-footer-link&quot;]/a[1]</value>
      <webElementGuid>b2b64b7b-6de7-41bc-ae72-6e8afa7e4edf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footercontent']/div[2]/div/div/div[3]/div/ul/li[2]/a</value>
      <webElementGuid>c7a40e78-d6d2-439b-b3cd-450de3e0f2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cartão Continente')])[3]</value>
      <webElementGuid>09e3ad5e-0d27-4f53-ab20-02aac0fdbfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.cartaocontinente.pt/?_gl=1*fmuffs*_ga*MTY1MDY2MjM1MC4xNzA3MjM4NTI0*_ga_56Q9X41Z3T*MTcwNzIzODUyMi4xLjAuMTcwNzIzODUyNy41OC4wLjA.')]</value>
      <webElementGuid>65c23ccc-0310-4087-ae59-bf1024c6dc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div[2]/div/div/div[3]/div/ul/li[2]/a</value>
      <webElementGuid>52fa9cbb-6dec-41aa-94e5-dc2fa1d7dbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.cartaocontinente.pt/?_gl=1*fmuffs*_ga*MTY1MDY2MjM1MC4xNzA3MjM4NTI0*_ga_56Q9X41Z3T*MTcwNzIzODUyMi4xLjAuMTcwNzIzODUyNy41OC4wLjA.' and @title = 'Go to Cartão Continente' and (text() = 'Cartão Continente' or . = 'Cartão Continente')]</value>
      <webElementGuid>a0a38362-3fb8-4749-98e2-0c672505ea2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
