<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Modelo Continente Hipermercados</name>
   <tag></tag>
   <elementGuidId>f7aa2fee-fc3a-4a9d-a202-5da399dc7871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footercontent']/div[2]/div/div/div[3]/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.col-md-4.d-none.d-md-block > div.content-asset > ul.ct-menu-list > li.ct-footer-link > a[title=&quot;Go to Modelo Continente Hipermercados&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6780ad38-923a-4340-9572-c4f2b8d24534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.continente.pt/continente-online/static-pages/about-us/</value>
      <webElementGuid>9fc6bf3f-45df-4f11-8808-25668484c54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go to Modelo Continente Hipermercados</value>
      <webElementGuid>6652fc27-b3cc-489c-b153-a79fa492317e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modelo Continente Hipermercados</value>
      <webElementGuid>e241d898-255f-4867-aa3f-283e7bdd8ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footercontent&quot;)/div[@class=&quot;container-fluid no-padding ct-modal-dialog-secondary-grey1 ct-font--opensans-book&quot;]/div[@class=&quot;pwc-container&quot;]/div[@class=&quot;row no-gutters footer-container pwc-container--px-70&quot;]/div[@class=&quot;col-12 col-md-4 d-none d-md-block&quot;]/div[@class=&quot;content-asset&quot;]/ul[@class=&quot;ct-menu-list&quot;]/li[@class=&quot;ct-footer-link&quot;]/a[1]</value>
      <webElementGuid>aca21330-b37d-4ed8-a935-586ee5e282dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footercontent']/div[2]/div/div/div[3]/div/ul/li/a</value>
      <webElementGuid>8cf067b0-f4b7-4306-9899-fd1f823d3d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Modelo Continente Hipermercados')])[2]</value>
      <webElementGuid>c064e98d-7ccf-400a-8c7e-cd3e0d19d13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.continente.pt/continente-online/static-pages/about-us/')])[2]</value>
      <webElementGuid>2749c7cb-2d15-4024-84db-a528c3137be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div[2]/div/div/div[3]/div/ul/li/a</value>
      <webElementGuid>3c1346ba-63e4-4128-9297-abc6487a0b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.continente.pt/continente-online/static-pages/about-us/' and @title = 'Go to Modelo Continente Hipermercados' and (text() = 'Modelo Continente Hipermercados' or . = 'Modelo Continente Hipermercados')]</value>
      <webElementGuid>9985ec5f-4c86-4a7a-8ddc-f1a667d94011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
