<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Segurana</name>
   <tag></tag>
   <elementGuidId>c2e0b9af-572e-43a6-af63-43380b5f9934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footercontent']/div[2]/div/div/div[3]/div/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.col-md-4.d-none.d-md-block > div.content-asset > ul.ct-menu-list > li.ct-footer-link > a[title=&quot;Segurança&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5430c9c5-1bb8-44ef-8f54-6acae0537ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://seguranca.continente.pt/?_gl=1*1n2u7oq*_ga*MTMxNTExMzQzMy4xNzA3MjMwMTkz*_ga_56Q9X41Z3T*MTcwNzIzMDE4OS4xLjAuMTcwNzIzMDE5Ni41OC4wLjA.</value>
      <webElementGuid>ec53985c-2fbc-4e28-ba75-7d6d1efe62e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Segurança</value>
      <webElementGuid>3256587e-1fca-41e0-beef-e201f91dc0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c400fc37-46f3-4b54-ac69-12b139547fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Segurança</value>
      <webElementGuid>5f555500-9796-4106-bcb6-60cc87daf987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footercontent&quot;)/div[@class=&quot;container-fluid no-padding ct-modal-dialog-secondary-grey1 ct-font--opensans-book&quot;]/div[@class=&quot;pwc-container&quot;]/div[@class=&quot;row no-gutters footer-container pwc-container--px-70&quot;]/div[@class=&quot;col-12 col-md-4 d-none d-md-block&quot;]/div[@class=&quot;content-asset&quot;]/ul[@class=&quot;ct-menu-list&quot;]/li[@class=&quot;ct-footer-link&quot;]/a[1]</value>
      <webElementGuid>e8084844-2fa9-42d5-976c-8fc2695a57ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footercontent']/div[2]/div/div/div[3]/div/ul/li[7]/a</value>
      <webElementGuid>fbb33938-ec18-4cf2-8442-6d63dc9d9494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Segurança')])[4]</value>
      <webElementGuid>aa851761-2c9e-4127-9b07-c4de07df88d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://seguranca.continente.pt/?_gl=1*1n2u7oq*_ga*MTMxNTExMzQzMy4xNzA3MjMwMTkz*_ga_56Q9X41Z3T*MTcwNzIzMDE4OS4xLjAuMTcwNzIzMDE5Ni41OC4wLjA.')]</value>
      <webElementGuid>9f10b203-0a31-4187-afe3-a2efb641adc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/ul/li[7]/a</value>
      <webElementGuid>e008a853-1498-4a71-b329-1b17932d65e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://seguranca.continente.pt/?_gl=1*1n2u7oq*_ga*MTMxNTExMzQzMy4xNzA3MjMwMTkz*_ga_56Q9X41Z3T*MTcwNzIzMDE4OS4xLjAuMTcwNzIzMDE5Ni41OC4wLjA.' and @title = 'Segurança' and (text() = 'Segurança' or . = 'Segurança')]</value>
      <webElementGuid>8078a0f1-c9d2-426c-b1e5-4e9159b34135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
