<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Permitir todos</name>
   <tag></tag>
   <elementGuidId>1358c1a1-cd77-4dcf-a720-02bed869e6b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61b2495e-e7fe-457b-94a1-28633bf60927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll</value>
      <webElementGuid>36a75d4c-2acc-4a21-93d6-309af60d39a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyButton</value>
      <webElementGuid>6932c7b2-d01b-4607-ab72-582f9550e8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f4f1ec7-9c15-457a-a527-7ee34a58c306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>pt</value>
      <webElementGuid>210e6630-b12e-4b30-9f47-8f8587f627a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permitir todos</value>
      <webElementGuid>9f0999b9-ea39-4363-b0bb-00cc15a285c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll&quot;)</value>
      <webElementGuid>e68522b7-07a8-44b6-961a-307d2be99fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll']</value>
      <webElementGuid>622b8d8c-c456-4a02-b595-2ba1f6c25d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CybotCookiebotDialogBodyButtonsWrapper']/button[4]</value>
      <webElementGuid>21e0b88e-6c1c-4574-a80c-71ce8d6575fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>23ee3cdd-bb1d-40f8-a8e7-3b4fe97e88ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll' and (text() = 'Permitir todos' or . = 'Permitir todos')]</value>
      <webElementGuid>0042c6f7-0c36-4de3-9773-a39f277979ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
