<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Poltica de Cookies (1)</name>
   <tag></tag>
   <elementGuidId>87eaf1b0-5543-4626-be29-96390a6b9cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CybotCookiebotDialogBodyContentTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='CybotCookiebotDialogBodyContentTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a4bdcfe5-7adb-4f33-8954-7f27ec665b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyContentTitle</value>
      <webElementGuid>e5c476f8-4645-4939-b463-9213101a607c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>pt</value>
      <webElementGuid>b1acc62f-9b4f-40b3-a248-6c5d773b8a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Política de Cookies</value>
      <webElementGuid>b98f7e5f-0ac8-42be-be88-94758efbeb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CybotCookiebotDialogBodyContentTitle&quot;)</value>
      <webElementGuid>6fb0045f-785b-4ea8-aeae-5c71906edb73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='CybotCookiebotDialogBodyContentTitle']</value>
      <webElementGuid>b40c3d15-0184-41c5-a6aa-076def6426e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CybotCookiebotDialogBodyContent']/h2</value>
      <webElementGuid>9eca3d0d-8c24-4d40-b262-f61a9931d1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>1947fa30-1efc-40d7-8993-ce54e0d7744c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'CybotCookiebotDialogBodyContentTitle' and (text() = 'Política de Cookies' or . = 'Política de Cookies')]</value>
      <webElementGuid>4f4c4936-3d59-44b0-913f-aeb5c727994b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
