<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_lazyloaded</name>
   <tag></tag>
   <elementGuidId>d982a4ae-e925-4f7c-a729-e0c3bdbaae48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slick-slide51 > div.experience-component.experience-commerce_assets-imageAndText > div.ITC-container.js-itc-container > div.row.ITC-row > div.col-12 > figure.ITC-figure.image-component > a.ITC-image-link > picture.intrinsic.intrinsic--itc-large > img.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide51']/div/div/div/div/figure/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ffa1b935-d5f8-4ab4-b71d-49cd625bf77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyloaded</value>
      <webElementGuid>ec05c3ab-05d3-4e99-85b0-aea55d2ed64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>97490c28-b6e6-405b-b009-142297d9b965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw50d6624b/images/homepage/continente-comunidade/2023/dezembro/s53-liga-portugal.jpg?sw=540&amp;sh=540&amp;sm=fit</value>
      <webElementGuid>21ae8238-7cc3-44e0-8ee3-9e0af97d94b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Liga Portugal</value>
      <webElementGuid>12cb7f46-d297-45b5-9370-19f7ad35b9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Liga Portugal</value>
      <webElementGuid>539a8773-9bf3-45ea-bda6-500cd05c0223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw50d6624b/images/homepage/continente-comunidade/2023/dezembro/s53-liga-portugal.jpg?sw=540&amp;sh=540&amp;sm=fit</value>
      <webElementGuid>879fa5ad-80d8-4f4b-bbd5-4d53b301e8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide51&quot;)/div[@class=&quot;experience-component experience-commerce_assets-imageAndText&quot;]/div[@class=&quot;ITC-container js-itc-container&quot;]/div[@class=&quot;row ITC-row&quot;]/div[@class=&quot;col-12&quot;]/figure[@class=&quot;ITC-figure image-component&quot;]/a[@class=&quot;ITC-image-link&quot;]/picture[@class=&quot;intrinsic intrinsic--itc-large&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>50d1d2c6-8e3b-4cbc-a6a6-be784bdde00e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide51']/div/div/div/div/figure/a/picture/img</value>
      <webElementGuid>ebd27e1e-b86d-4717-aac5-f0c8cacdd4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Liga Portugal']</value>
      <webElementGuid>1863784e-9339-4338-837e-4e7978b4aebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div/div/figure/a/picture/img</value>
      <webElementGuid>d6f260a2-8b55-4f3a-a094-c27b68467bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Liga Portugal' and @title = 'Liga Portugal' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw50d6624b/images/homepage/continente-comunidade/2023/dezembro/s53-liga-portugal.jpg?sw=540&amp;sh=540&amp;sm=fit']</value>
      <webElementGuid>9b912d99-949d-48cd-8c96-6619f232c629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
