<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ajuda</name>
   <tag></tag>
   <elementGuidId>9226768e-19b0-4e4e-bf1b-7331a5355b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='brand-header']/div[2]/div/div/ul[2]/li[2]/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.d-flex.align-items-center.bold-on-hover--md-up > span:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e59cf18d-0d31-4e9e-af3c-8b0966e021a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajuda</value>
      <webElementGuid>ec0f21b8-d7ef-465d-83fb-5aa3e2e802d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brand-header&quot;)/div[@class=&quot;header-links ct-dropdown--desktop js-header-links-desktop&quot;]/div[@class=&quot;col-12 p-md-0 header-util&quot;]/div[@class=&quot;header-util-wrap&quot;]/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item get-help d-none d-sm-block&quot;]/a[@class=&quot;nav-link d-flex align-items-center bold-on-hover--md-up&quot;]/span[2]</value>
      <webElementGuid>7797fae7-764a-47ee-88d6-c78d8a61e76c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='brand-header']/div[2]/div/div/ul[2]/li[2]/a/span[2]</value>
      <webElementGuid>349a49e4-27d9-4a2b-ba80-8ac743ae9da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]</value>
      <webElementGuid>3fd28ab0-a039-45d8-b40d-40eaa584c76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ajuda' or . = 'Ajuda')]</value>
      <webElementGuid>b489993b-819b-44db-8a6d-dc2bb126e2fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
