<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LigaPortugal</name>
   <tag></tag>
   <elementGuidId>ea17378e-3182-4d21-8000-ce536df61ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slick-slide11 > div.experience-component.experience-commerce_assets-imageAndText > div.ITC-container.js-itc-container > div.row.ITC-row > div.col-12 > figure.ITC-figure.image-component > a.ITC-image-link > picture.intrinsic.intrinsic--itc-large > img.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide11']/div/div/div/div/figure/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2630ac44-e8cb-4a50-bced-8d6d97cd0f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyloaded</value>
      <webElementGuid>64e57a84-5d5e-4255-b436-f44094a6a587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>60317c83-5be2-49ff-8b41-821f28a033bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw50d6624b/images/homepage/continente-comunidade/2023/dezembro/s53-liga-portugal.jpg?sw=540&amp;sh=540&amp;sm=fit</value>
      <webElementGuid>23947227-6b1c-467b-88c4-26aad5cdee03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Liga Portugal</value>
      <webElementGuid>11f75b79-abad-4cca-8c8b-90afc75cda84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Liga Portugal</value>
      <webElementGuid>5dde9d88-a23d-44dc-b229-d4d0e8997530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw50d6624b/images/homepage/continente-comunidade/2023/dezembro/s53-liga-portugal.jpg?sw=540&amp;sh=540&amp;sm=fit</value>
      <webElementGuid>99b12d78-36ae-4a7a-86b9-ba9d950a4bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide11&quot;)/div[@class=&quot;experience-component experience-commerce_assets-imageAndText&quot;]/div[@class=&quot;ITC-container js-itc-container&quot;]/div[@class=&quot;row ITC-row&quot;]/div[@class=&quot;col-12&quot;]/figure[@class=&quot;ITC-figure image-component&quot;]/a[@class=&quot;ITC-image-link&quot;]/picture[@class=&quot;intrinsic intrinsic--itc-large&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>a03f0878-4931-4b2b-b79a-f67aca166818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide11']/div/div/div/div/figure/a/picture/img</value>
      <webElementGuid>c81acd7f-6bc5-4f95-bc53-9c809c2372d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Liga Portugal']</value>
      <webElementGuid>cc9f9781-7f06-4ac2-a3de-5eba385308af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div/div/figure/a/picture/img</value>
      <webElementGuid>65b00429-25cf-40e0-87a1-a7be07468724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Liga Portugal' and @title = 'Liga Portugal' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dw50d6624b/images/homepage/continente-comunidade/2023/dezembro/s53-liga-portugal.jpg?sw=540&amp;sh=540&amp;sm=fit']</value>
      <webElementGuid>5f7b8897-b41f-441c-8543-beb9370a0346</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
