<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_LoginRegisto_svg-inline icon-arrow-down</name>
   <tag></tag>
   <elementGuidId>2325f73b-de78-4efc-9cfa-6840c26350b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/header/nav/div/div[2]/div/nav/div/ul/li[1]/div[1]/span/svg/path</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.svg-inline.icon-arrow-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sg-navbar-collapse&quot;]/div/nav/div/ul/li[1]/div[1]/span/svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>0130e61c-d8ac-4e8d-97d4-1a6dba87637a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline icon-arrow-down</value>
      <webElementGuid>1992fe46-aaa5-435b-98d1-b6c20fd90977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>c2c331fb-3bcb-4426-b902-23aabe46998b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 12 13</value>
      <webElementGuid>060e63fd-cef0-43ad-8484-2211b8573997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>86aa5da2-18ca-4f2b-aa60-aff23aaae245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e652a74d-43a2-4c93-a820-522507f04e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/header/nav/div/div[2]/div/nav/div/ul/li[1]/div[1]/span/svg/path</value>
      <webElementGuid>874c77ee-37bc-4c57-8026-1cd570c7b46f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
